[WIP Actions subpage
hoprnet/hopr-admin pull request #159
Opened 2023-07-27 00:25 UTC by diegoalzate

closes #137 

### overview
merge pending transactions and history transactions into one new page called actions.

### why wip/

2023-07-28 09:24 UTC, mjadach-iv commented
So far I only get here:
```
Encoded function signature "0x0d582f13" not found on ABI. Make sure you are using the correct ABI and that the function exists on it. You can look up the signature here: https://openchain.xyz/signatures?query=0x0d582f13. Docs: https://viem.sh/docs/contract/decodeFunctionData.html Version: viem@1.2.12`


AbiFunctionSignatureNotFoundError: Encoded function signature "0x0d582f13" not found on ABI.
Make sure you are using the correct ABI and that the function exists on it.
You can look up the signature here: https://openchain.xyz/signatures?query=0x0d582f13.

Docs: https://viem.sh/docs/contract/decodeFunctionData.html
Version: viem@1.2.12
    at decodeFunctionData (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-IOZXXKPR.js?v=e2830c19:2762:11)
    at getRequest (http://127.0.0.1:5173/src/sections/actions.tsx:922:27)
    at http://127.0.0.1:5173/src/sections/actions.tsx:903:17
    at commitHookEffectListMount (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-IO73RGX3.js?v=e2830c19:16912:34)
    at invokePassiveEffectMountInDEV (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-IO73RGX3.js?v=e2830c19:18328:19)
    at invokeEffectsInDev (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-IO73RGX3.js?v=e2830c19:19705:19)
    at commitDoubleInvokeEffectsInDEV (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-IO73RGX3.js?v=e2830c19:19690:15)
    at flushPassiveEffectsImpl (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-IO73RGX3.js?v=e2830c19:19507:13)
    at flushPassiveEffects (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-IO73RGX3.js?v=e2830c19:19451:22)
    at commitRootImpl (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-IO73RGX3.js?v=e2830c19:19420:13)
``

2023-07-28 16:29 UTC, diegoalzate commented
> So far I only get here:
> 
> ```
> Encoded function signature "0x0d582f13" not found on ABI. Make sure you are using the correct ABI and that the function exists on it. You can look up the signature here: https://openchain.xyz/signatures?query=0x0d582f13. Docs: https://viem.sh/docs/contract/decodeFunctionData.html Version: viem@1.2.12`
> 
> 
> AbiFunctionSignatureNotFoundError: Encoded function signature "0x0d582f13" not found on ABI.
> Make sure you are using the correct ABI and that the function exists on it.
> You can look up the signature here: https://openchain.xyz/signatures?query=0x0d582f13.
> 
> Docs: https://viem.sh/docs/contract/decodeFunctionData.html
> Version: viem@1.2.12
>     at decodeFunctionData (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-IOZXXKPR.js?v=e2830c19:2762:11)
>     at getRequest (http://127.0.0.1:5173/src/sections/actions.tsx:922:27)
>     at http://127.0.0.1:5173/src/sections/actions.tsx:903:17
>     at commitHookEffectListMount (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-IO73RGX3.js?v=e2830c19:16912:34)
>     at invokePassiveEffectMountInDEV (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-IO73RGX3.js?v=e2830c19:18328:19)
>     at invokeEffectsInDev (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-IO73RGX3.js?v=e2830c19:19705:19)
>     at commitDoubleInvokeEffectsInDEV (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-IO73RGX3.js?v=e2830c19:19690:15)
>     at flushPassiveEffectsImpl (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-IO73RGX3.js?v=e2830c19:19507:13)
>     at flushPassiveEffects (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-IO73RGX3.js?v=e2830c19:19451:22)
>     at commitRootImpl (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-IO73RGX3.js?v=e2830c19:19420:13)
> ``
> ```

Very interesting bug, so what is happening here is that to get the functionName of the transaction data we have to know what we are looking for. This means we can only decode transactions from abis that we expect. As of right now we expect transactions from  any erc20ABI, erc4626ABI, erc721ABI and safeABI. When we fail to decode it will say that to the user instead of throwing an error.

2023-08-02 12:43 UTC, mjadach-iv requested changes
- The Notifications should point to the new page, now we get an error when clicking on them
- when hovering the source ETH address we should have a tooltip with a whole address in it

Btw, history seems to have randomly disabled/grayed out entries, why?

2023-08-03 15:17 UTC, mjadach-iv requested changes

2023-08-07 07:45 UTC, mjadach-iv approved these changes

2023-08-07 07:45 UTC, merged