Ws connection middleware for redux
hoprnet/hopr-admin pull request #25
Opened 2023-05-30 21:06 UTC by diegoalzate

### How does this work? 
[redux middleware](https://redux.js.org/understanding/history-and-design/middleware#the-final-approach)  It provides a third-party extension point between dispatching an action, and the moment it reaches the reducer. So when a initializeWebsocket action is triggered it will first run run through the middleware creating a websocket connection before reaching the actual reducer.

### Why?
The WebSocket instance is not serializable and thus technically not something that should be stored in Redux state. So there were 2 alternatives considered in this pr:

#### [rtk query streaming updates](https://redux-toolkit.js.org/rtk-query/usage/streaming-updates)
With this solution we could have an easy way to mount ws connection and tear it down, however there are a lot of concepts the team would need to learn and it also provides less customization. 

#### custom redux middleware
Even though this solution is more code, the concept of middleware is easier to understand and provides us a solution that can adapter better to any changes that may happen on hoprd side.

### why was LocalRootState created?
The middleware has access to the whole store, however I could not reference the store type inside the actual middleware because the middleware will be used in the store. That would create a circular dependency. We could create the RootStore type by hand instead of inferring but I think the store is more likely to change than the middleware.

### How can this be better?
- add common ws logic to hopr-sdk and use it here

2023-05-31 20:53 UTC, diegoalzate commented
blocked by https://github.com/hoprnet/hopr-sdk/pull/56

2023-06-02 08:07 UTC, mjadach-iv commented
Lets wait with merge until older PRs are merged.

2023-06-02 14:20 UTC, mjadach-iv requested changes
Rebase needed

2023-06-05 08:29 UTC, mjadach-iv commented on src/store/slices/node/websocketMiddleware.ts
> +          '/api/v2/messages/websocket/',
shouldn't this part be provided by the HOPR-SDK?

2023-06-05 08:31 UTC, mjadach-iv commented on src/store/slices/node/websocketMiddleware.ts
> +            url: wsUrl,
We should update the WebsocketHelper to comly with the apiEndpoint and apiToken standard we have in all the other calls, and then use it here

2023-06-07 15:07 UTC, mjadach-iv approved these changes

2023-06-07 15:08 UTC, merged