Update .prettierrc.json
hoprnet/hopr-admin pull request #26
Opened 2023-05-30 21:58 UTC by camilovegag

Adding some of the `.prettierrc.json` options that we use at hoprnet-org.

Of course we can check if those options are ok for us

https://prettier.io/docs/en/options.html

2023-05-30 23:27 UTC, ItsLuized approved these changes

2023-06-02 07:32 UTC, mjadach-iv commented
Lets wait with merge until older PRs are merged.

2023-06-02 14:21 UTC, mjadach-iv requested changes
Rebase needed

2023-06-02 14:21 UTC, mjadach-iv commented on .prettierrc.json
> +  "printWidth": 80,
Lets make it 120

2023-06-02 22:07 UTC, camilovegag commented on .prettierrc.json
> +  "printWidth": 80,
Updated

2023-06-06 10:59 UTC, mjadach-iv commented on src/future-hopr-lib-components/NFT/nftImageInteractive.jsx
> +            className={['nft-image-container', props.ignored ? 'ignored' : ''].join(' ')}
@camilovegag, please check if we can make an exception for arrays in props to have singleAttributePerLine

2023-06-06 11:00 UTC, mjadach-iv commented on src/App.tsx
> +import { RouterProvider, BrowserRouter, Route, createRoutesFromElements, createBrowserRouter } from 'react-router-dom';
@camilovegag, please check if we can make an exception for imports to have singleAttributePerLine

2023-06-06 11:01 UTC, mjadach-iv commented on src/future-hopr-lib-components/Layout/index.tsx
> +}> = ({ className = '', children, itemsNavbarRight, tallerNavBarOnMobile, drawer, drawerItems }) => {
@camilovegag, please check if we can make an exception for destructuring like this one to have singleAttributePerLine

2023-06-06 11:01 UTC, mjadach-iv commented
The branch is rebased onto current develop

2023-06-15 01:47 UTC, camilovegag commented
Closing as this will be addressed on #56

2023-06-15 01:47 UTC, closed without merging