Dashboard in place
hoprnet/hopr-admin pull request #307
Opened 2023-08-31 15:39 UTC by mjadach-iv

2023-08-31 20:27 UTC, diegoalzate requested changes

2023-08-31 20:27 UTC, diegoalzate commented on src/components/ConnectSafe/index.tsx
> +   //   getOnboardingData(safeAddress);
why comment this out again?

2023-09-01 07:16 UTC, merged

2023-09-01 07:16 UTC, mjadach-iv commented on src/components/ConnectSafe/index.tsx
> +   //   getOnboardingData(safeAddress);
Fixed

2023-09-01 07:16 UTC, mjadach-iv commented
Had to publish, no time to wait for re-review.