Feedback on chain component
hoprnet/hopr-admin pull request #368
Opened 2023-09-07 21:24 UTC by diegoalzate

closes #354 

### overview
created a `FeedbackTransaction` that receives 

```
{
  transactionHash?: Address;
  confirmations: number;
  feedbackTexts: {
    loading: string;
    idle?: string;
    success?: string;
    error?: string;
  };
}
```

Depending on the status of the transaction hash it will show the feedback text. Confirmation number allows customization on how long we would want to wait to make sure a tx went through.

### ui
![CleanShot 2023-09-07 at 16 20 29](https://github.com/hoprnet/hopr-admin/assets/22416585/bcdfe9e1-f131-4eb7-b25c-2f4cb10cf005)

2023-09-08 06:51 UTC, mjadach-iv requested changes
Please use this component in all places that require wallet confirm

2023-09-08 06:51 UTC, mjadach-iv commented on config.ts
> +export const MINIMUM_XDAI_TO_FUND_NODE = 0.01;
Need to revert that

2023-09-08 19:00 UTC, diegoalzate commented
> Please use this component in all places that require wallet confirm

Added to fund node but did not add it to sign functions because we do not wait on those. Also reverted the minimum values.

2023-09-12 10:06 UTC, mjadach-iv requested changes
- not present on 'staking/withdraw' path
- not present on 'staking/stake-wxHOPR' path
- not present on 'staking/fund-node' path

2023-09-14 07:05 UTC, mjadach-iv requested changes
Still doesn't show on some components, eg:
![image](https://github.com/hoprnet/hopr-admin/assets/104129084/52dbec87-c460-4948-b81b-86fcb89a5a9d)

2023-09-14 15:06 UTC, diegoalzate commented
> Still doesn't show on some components, eg: ![image](https://user-images.githubusercontent.com/104129084/267886156-52dbec87-c460-4948-b81b-86fcb89a5a9d.png)

added a isWalletPendingState for this use case

2023-09-18 07:58 UTC, mjadach-iv requested changes
Right now the `/staking/withdraw` is jumping when we press 'Execute' because the Feedback component is showing up. It also might be the case on other components.
It would be best to make the component have min-height of its normal height when displayed, so when the status would show, nothing would be moving around on the scren

2023-09-21 09:42 UTC, merged