Add notifications for safe xdai and safe wxHopr
hoprnet/hopr-admin pull request #380
Opened 2023-09-08 20:53 UTC by ItsLuized

Fixes #371 

### Overview

Add balance notifications for when Safe receives xDai or wxHopr.

### Definition of Done
For receiving funds there should be only following notifications:

- [x] Node received xDai
- [x] Safe received xDai
- [x] Safe received wxHOPR

<img width="173" alt="image" src="https://github.com/hoprnet/hopr-admin/assets/32660456/fa79e9e6-ffbd-46b1-844a-28aa937a82ee">

2023-09-11 17:04 UTC, diegoalzate requested changes

2023-09-11 17:04 UTC, diegoalzate commented on src/hooks/useWatcher/balances.ts
> +              name: 'Safe received wxHop',
typo

2023-09-11 18:10 UTC, diegoalzate approved these changes

2023-09-12 10:09 UTC, mjadach-iv approved these changes

2023-09-12 10:09 UTC, merged