Multiple node balances and details
hoprnet/hopr-admin pull request #504
Opened 2024-01-10 16:30 UTC by mjadach-iv

2024-01-10 17:49 UTC, Jaguaras requested changes
Please leave 2 decimals, it should be enough. Because small screens ( with resolution 3024 × 1964) can't see much.

2024-01-11 06:56 UTC, esterlus approved these changes
found a code optimization with forEach

2024-01-11 06:56 UTC, esterlus commented on src/store/slices/stakingHub/actionsAsync.ts
> +      if (output.registeredNodesInSafeRegistry?.length > 0) {
```  
    output.registeredNodesInSafeRegistry?.forEach(safeRegNode => {
          let nodeAddress = safeRegNode.node.id;
          dispatch(getNodeDataThunk({nodeAddress, browserClient}));
        })
```

2024-01-12 14:28 UTC, mjadach-iv commented on src/store/slices/stakingHub/actionsAsync.ts
> +      if (output.registeredNodesInSafeRegistry?.length > 0) {
Updated

2024-01-12 15:35 UTC, Jaguaras approved these changes
lgtm!

2024-01-12 15:36 UTC, merged